routes/web.php
<?php

use App\Http\Middleware\Admin;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\CartController;
// use App\Http\Controllers\CartDetailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Illuminate\Support\Facades\Auth::routes();

    // Route::get('/checkout/{id}', [ProdukController::class, 'checkout'])->name('checkout');
    // Route::get('/keranjang', 'ProdukController@checkout');
    // Route::resource('detail-transaksi', \App\Http\Controllers\DetailTransaksiController::class);

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::resource('produk', \App\Http\Controllers\ProdukController::class);
    Route::resource('cart', \App\Http\Controllers\CartController::class);
    Route::get('cartindex', [\App\Http\Controllers\CartController::class, 'isicart']);
    Route::resource('transaksi', App\Http\Controllers\TransaksiController::class);

    Route::middleware('admin')->group(function () {
        Route::resource('kategori', \App\Http\Controllers\KategoriController::class);
        Route::get('kategoriindex',[App\Http\Controllers\KategoriController::class, 'isikategori']);
        Route::resource('genre', \App\Http\Controllers\GenreController::class);
        Route::get('genreindex',[App\Http\Controllers\GenreController::class, 'isigenre']);
        Route::resource('penerbit', \App\Http\Controllers\PenerbitController::class);
        Route::get('penerbitindex',[App\Http\Controllers\PenerbitController::class, 'isipenerbit']);
        Route::resource('cara_bayar', \App\Http\Controllers\CaraBayarController::class);
        Route::resource('pengiriman', \App\Http\Controllers\PengirimanController::class);
    });

    // Route::middleware('user')->group(function () {
    //     Route::resource('transaksi', \App\Http\Controllers\TransaksiController::class);
    //     // cart
    //     Route::resource('cart', \App\Http\Controllers\CartController::class);
    //     Route::patch('kosongkan/{id}', [App\Http\Controllers\CartController::class, 'kosongkan']);\
    // });

// Route::group(['middleware' => 'auth'], function() {
    // cart
    // Route::resource('cart', \App\Http\Controllers\CartController::class);
    // Route::patch('kosongkan/{id}', [App\Http\Controllers\CartController::class, 'kosongkan']);
    // cart detail
    // Route::resource('cartdetail', \App\Http\Controllers\CartDetailController::class);
//   });

    

app/Http/Controllers/PengirimanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PengirimanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['pengiriman'] = Delivery::all();
        return view('admin.pengiriman.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pengiriman.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Start Validation
        $rules = [
            'pengiriman' => 'required|unique:delivery',
        ];

        $customMessages = [
            'pengiriman.required' => 'pengiriman wajib diisi!',
            'pengiriman.unique' => 'pengiriman sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $input = $request->all();
        $status = Delivery::create($input);

        if ($status){
            return redirect()->route('pengiriman.index')->with('success', 'Data Warna berhasil ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pengiriman'] = Delivery::find($id);
        return view('admin.pengiriman.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Start Validation
        $rules = [
            'pengiriman' => 'required|unique:delivery',
        ];

        $customMessages = [
            'pengiriman.required' => 'pengiriman wajib diisi!',
            'pengiriman.unique' => 'pengiriman sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $pengiriman = Delivery::find($id);
        $update = $request->all();
        $status = $pengiriman->update($update);

        if ($status){
            return redirect()->route('pengiriman.index')->with('success', 'Data berhasil diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pengiriman = Delivery::find($id);
        $status = $pengiriman->delete();
        if ($status){
            return 1;
        }else{
            return 0;
        }

    }

}

resources/views/admin/pengiriman/form.blade.php
@extends('admin.layouts.app')
@section('pengiriman', 'active')
@section('title')
     Form {{@$pengiriman ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Tambah Pengiriman</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('pengiriman.index')}}">Pengiriman</a>
                                </li>
                                <li class="breadcrumb-item active">Form Pengiriman
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Vertical form layout section start -->
            <section id="basic-vertical-layouts">
                <div class="row">
                    <div class="col-md-6 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Form pengiriman</h4>
                            </div>
                            <div class="card-body">
                                @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                <form class="form form-vertical" action="{{@$pengiriman ? route('pengiriman.update',$pengiriman->id) : route('pengiriman.store')}}"
                                    method="POST" enctype="multipart/form-data">
                                @csrf
                                @if(@$pengiriman)
                                    {{method_field('patch')}}
                                @endif
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="pengiriman">pengiriman</label>
                                                <input type="text" id="pengiriman" class="form-control" name="pengiriman" placeholder="pengiriman" value="{{old('nama', @$pengiriman ? $pengiriman->pengiriman : '')}}" />
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                            <a href="{{route('pengiriman.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Basic Vertical form layout section end -->

        </div>
    </div>
</div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/pengiriman/index.blade.php
@extends('admin.layouts.app')
@section('pengiriman', 'active')
@section('title','Data pengiriman')

@section('content')

<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Data pengiriman</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Data pengiriman
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('pengiriman.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah pengiriman</a>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>pengiriman</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($pengiriman as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->pengiriman}}</td>
                                            <td>
                                                <a href="{{route('pengiriman.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
        </div>
    </div>
</div>
@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btn-del', function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url('pengiriman')}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        location.reload();
                                    } else {
                                        toastr.error('Data gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush