routes/web.php
<?php

use App\Http\Middleware\Admin;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
// use App\Http\Controllers\CartController;
// use App\Http\Controllers\CartDetailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Illuminate\Support\Facades\Auth::routes();

    // Route::get('/checkout/{id}', [ProdukController::class, 'checkout'])->name('checkout');
    // Route::get('/keranjang', 'ProdukController@checkout');
    // Route::resource('detail-transaksi', \App\Http\Controllers\DetailTransaksiController::class);

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
    Route::resource('produk', \App\Http\Controllers\ProdukController::class);
    Route::resource('cart', \App\Http\Controllers\CartController::class);
    Route::get('cartindex', [\App\Http\Controllers\CartController::class, 'isicart']);
    Route::resource('transaksi', App\Http\Controllers\TransaksiController::class);

    Route::middleware('admin')->group(function () {
        Route::resource('kategori', \App\Http\Controllers\KategoriController::class);
        Route::get('kategoriindex',[App\Http\Controllers\KategoriController::class, 'isikategori']);
        Route::resource('genre', \App\Http\Controllers\GenreController::class);
        Route::get('genreindex',[App\Http\Controllers\GenreController::class, 'isigenre']);
        Route::resource('penerbit', \App\Http\Controllers\PenerbitController::class);
        Route::get('penerbitindex',[App\Http\Controllers\PenerbitController::class, 'isipenerbit']);
        Route::resource('cara_bayar', \App\Http\Controllers\CaraBayarController::class);
        Route::resource('pengiriman', \App\Http\Controllers\PengirimanController::class);
    });

    // Route::middleware('user')->group(function () {
    //     Route::resource('transaksi', \App\Http\Controllers\TransaksiController::class);
    //     // cart
    //     Route::resource('cart', \App\Http\Controllers\CartController::class);
    //     Route::patch('kosongkan/{id}', [App\Http\Controllers\CartController::class, 'kosongkan']);\
    // });

// Route::group(['middleware' => 'auth'], function() {
    // cart
    // Route::resource('cart', \App\Http\Controllers\CartController::class);
    // Route::patch('kosongkan/{id}', [App\Http\Controllers\CartController::class, 'kosongkan']);
    // cart detail
    // Route::resource('cartdetail', \App\Http\Controllers\CartDetailController::class);
//   });

    

app/Http/Controllers/CaraBayarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CaraBayarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['cara_bayar'] = PaymentOption::all();
        return view('admin.cara_bayar.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cara_bayar.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Start Validation
        $rules = [
            'cara_bayar' => 'required|unique:cara_bayar',
        ];

        $customMessages = [
            'cara_bayar.required' => 'cara_bayar wajib diisi!',
            'cara_bayar.unique' => 'cara_bayar sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $input = $request->all();
        $status = PaymentOption::create($input);

        if ($status){
            return redirect()->route('cara_bayar.index')->with('success', 'Data berhasil ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['cara_bayar'] = PaymentOption::find($id);
        return view('admin.cara_bayar.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Start Validation
        $rules = [
            'cara_bayar' => 'required|unique:cara_bayar',
        ];

        $customMessages = [
            'cara_bayar.required' => 'cara_bayar wajib diisi!',
            'cara_bayar.unique' => 'cara_bayar sudah digunakan!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $cara_bayar = PaymentOption::find($id);
        $update = $request->all();
        $status = $cara_bayar->update($update);

        if ($status){
            return redirect()->route('cara_bayar.index')->with('success', 'Data berhasil diubah');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cara_bayar = PaymentOption::find($id);
        $status = $cara_bayar->delete();
        if ($status){
            return 1;
        }else{
            return 0;
        }

    }

}

resources/views/admin/cara_bayar/form.blade.php
@extends('admin.layouts.app')
@section('cara_bayar', 'active')
@section('title')
     Form {{@$cara_bayar ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Tambah Cara Bayar</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="{{route('cara_bayar.index')}}">Cara Bayar</a>
                                </li>
                                <li class="breadcrumb-item active">Form Cara Bayar
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Vertical form layout section start -->
            <section id="basic-vertical-layouts">
                <div class="row">
                    <div class="col-md-6 col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Form Cara Bayar</h4>
                            </div>
                            <div class="card-body">
                                @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                <form class="form form-vertical" action="{{@$cara_bayar ? route('cara_bayar.update',$cara_bayar->id) : route('cara_bayar.store')}}"
                                    method="POST" enctype="multipart/form-data">
                                @csrf
                                @if(@$cara_bayar)
                                    {{method_field('patch')}}
                                @endif
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="cara_bayar">Cara Bayar</label>
                                                <input type="text" id="cara_bayar" class="form-control" name="cara_bayar" placeholder="cara_bayar" value="{{old('nama', @$cara_bayar ? $cara_bayar->cara_bayar : '')}}" />
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                            <a href="{{route('cara_bayar.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Basic Vertical form layout section end -->

        </div>
    </div>
</div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/cara_bayar/index.blade.php
@extends('admin.layouts.app')
@section('cara_bayar', 'active')
@section('title','Data cara_bayar')

@section('content')

<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Data Cara Bayar</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Data Cara Bayar
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic Tables start -->
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('cara_bayar.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Cara Bayar</a>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Cara Bayar</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($cara_bayar as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->cara_bayar}}</td>
                                            <td>
                                                <a href="{{route('cara_bayar.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Basic Tables end -->
        </div>
    </div>
</div>
@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btn-del', function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url('cara_bayar')}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        location.reload();
                                    } else {
                                        toastr.error('Data gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush